name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Correctness
      id: correctness
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Correctness
        setup-command: ''
        command: "[ -f fibonacci.py ] && python3 src/fibonacci.py ${input} || Rscript src/fibonacci.R ${input}"
        input: '1'
        expected-output: '1'
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CORRECTNESS_RESULTS: "${{steps.correctness.outputs.result}}"
      with:
        runners: correctness
